#!/bin/bash


. ./get_day_year

cookie=`cat .aoc_cookie`
if [ "$cookie" = "" ]; then
    echo "Missing cookie"
    exit 6
fi

day_url=$(expr $day + 0)

mkdir -p data/$year
mkdir data/$year/day$day
touch data/$year/day$day/test.txt
curl --cookie "$cookie" https://adventofcode.com/$year/day/$day_url/input > data/$year/day$day/input.txt
