#!/bin/bash

day=$1
year=$2

year_with_default=2024

profile=$3

if [ "$day" = "" ]; then
    echo "Missing day"
    exit 1
fi
if [ $day -lt 10 ]; then
    day="0$day"
fi

binaryname=day$day
if [ "$year" != "" ] && [ "$year" != 2024 ]; then
    binaryname="$binaryname-$year"
    year_with_default="$year"
fi

BASE_CMD="cargo run -q"
if [ "$profile" = "flamegraph" ]; then
    BASE_CMD="sudo cargo flamegraph"
fi

CMD="$BASE_CMD --bin $binaryname"

if [ "$profile" = "release" ]; then
    CMD="$CMD --release"
fi
if [ "$profile" = "flamegraph" ]; then
    CMD="$CMD --profile flamegraph"
#    CMD="$CMD --dev"
fi

if [ "$profile" = "nobuild" ]; then
    if [ "$$CARGO_TARGET_DIR" = "" ]; then
        CARGO_TARGET_DIR="target"
    fi
    CMD="./$CARGO_TARGET_DIR/release/$binaryname"
fi

echo "Year $year_with_default, Day $day"
$CMD
echo