#!/bin/bash


. ./get_day_year

profile=$3

binaryname=day$day-$year

BASE_CMD="cargo run -q"
if [ "$profile" = "flamegraph" ]; then
    BASE_CMD="sudo cargo flamegraph"
fi

CMD="$BASE_CMD --bin $binaryname"

if [ "$profile" = "release" ]; then
    CMD="$CMD --release"
fi
if [ "$profile" = "flamegraph" ]; then
    CMD="$CMD --profile flamegraph"
#    CMD="$CMD --dev"
fi

if [ "$profile" = "nobuild" ]; then
    if [ "$$CARGO_TARGET_DIR" = "" ]; then
        CARGO_TARGET_DIR="target"
    fi
    CMD="./$CARGO_TARGET_DIR/release/$binaryname"
fi

echo "Year $year, Day $day"
$CMD
echo