[package]
name = "aoc_tools"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["blocking"] }

[dependencies.xxhash-rust]
version = "0.8.5"
features = ["xxh3"]
